services:
  backend:
    image: rest-api-flask
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}-backend"
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:13
    container_name: "${PROJECT_NAME}-db"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
#      POSTGRES_PASSWORD: "${PG_PASS}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "restapi_db"
      POSTGRES_USER: "postgres"
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U restapi", "-d", "restapi_db"]
      timeout: 60s
      retries: 5
      start_period: 80s
      interval: 30s
    restart: always

volumes:
  pg_data:
