CREATE USER restapi WITH SUPERUSER ENCRYPTED PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE restapi_db TO restapi;

CREATE TABLE lessons (id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL);
CREATE TABLE themes (lesson_id INTEGER, theme VARCHAR(255), FOREIGN KEY(lesson_id) REFERENCES lessons(id) ON DELETE CASCADE);


